# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: System Administrator trying to do his job...
email: jo.vandeginste@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Linux SysAdmin at a university's central IT department, learning some
  new (to me) tools and usually struggling to get them working in our corporate
  environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jovandeginste.github.io" # the base hostname & protocol for your site
twitter_username: jo_vdg
github_username:  jovandeginste

# Build settings
markdown: kramdown
