# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another SysAdmin trying to do his job...
name: Jo Vandeginste
email: jo.vandeginste@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Linux SysAdmin at a university's central IT department. I try to learn some
  new (to me) tools and usually struggle to get them working in our corporate
  environment.
  <p>Found something very useful and feel grateful? Consider donating!</p>
  <p><i class="fa fa-btc" style="color: #F69619"></i> 1E7z4Z7R92WbZ1GHPH7zApSkvxduPMu1y7</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jovandeginste.github.io" # the base hostname & protocol for your site
twitter_username: jo_vdg
github_username:  jovandeginste
linkedin_username: jovandeginste
google_plus_username: jovandeginste

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jemoji
